Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2024-12, with the labels that each got.

#220 Fix the opening of notebooks in a new tab when using the `JupyterLite` and `Voici` directives
  docs/full.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: maintenance

#224 Fix paths for Replite apps
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#223 Add an option to open the Notebook UI and Voici apps in a new tab via the`NotebookLite` and `Voici` directives
  docs/directives/jupyterlite.md
  docs/directives/notebooklite.md
  docs/directives/voici.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#225 Allow the use of a custom `overrides.json` file for configuring JupyterLite at runtime
  docs/conf.py
  docs/configuration.md
  docs/sample_overrides.json
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#227 Allow global and custom button text for the new-tabbed variants of the `JupyterLite`, `NotebookLite`, and the `Voici` directives
  docs/configuration.md
  docs/directives/jupyterlite.md
  docs/directives/notebooklite.md
  docs/directives/voici.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#229 Bump OS image and dependencies for Read the Docs build config
  .readthedocs.yml
Labels: maintenance

#233 Switch to Miniforge and drop Mambaforge
  .github/workflows/main.yml
Labels: maintenance

#228 Add a new-tabbed variant for the `Replite` directive, and allow customisation of its button text
  docs/configuration.md
  docs/directives/jupyterlite.md
  docs/directives/notebooklite.md
  docs/directives/replite.md
  docs/directives/voici.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#221 Support the usage of Markdown-based notebooks with "Lite" directives
  dev-environment.yml
  docs/configuration.md
  docs/directives/jupyterlite.md
  docs/directives/my_markdown_notebook.md
  docs/directives/notebooklite.md
  docs/directives/voici.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
  pyproject.toml
Labels: enhancement

#235 Add some spacing below the Lite iframes
  jupyterlite_sphinx/jupyterlite_sphinx.css
Labels: enhancement, maintenance

#236 Add missing dependency on `jupytext`
  pyproject.toml
Labels: maintenance

#239 Drop Python 3.8
  pyproject.toml
Labels: maintenance

#238 Relax `jupyterlite-core` and `jupyterlite-xeus` dependencies
  dev-environment.yml
  pyproject.toml
Labels: maintenance
