Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2024-03, with the labels that each got.

#141 Hide buttons on smaller screens (mobile).
  docs/directives/try_examples.md
  jupyterlite_sphinx/jupyterlite_sphinx.css
Labels: enhancement

#145 Run pre-commit on all files in this repository.
  jupyterlite_sphinx/jupyterlite_sphinx.css
  jupyterlite_sphinx/jupyterlite_sphinx.js
Labels: maintenance

#143 Add option for initial warning cell in try examples directive
  docs/directives/try_examples.md
  jupyterlite_sphinx/_try_examples.py
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#148 ENH: Add metadata for parallel_read_safe = True
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#150 Set lower default verbosity and add config options.
  docs/configuration.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#153 Give a pragmatic solution to suppressing noisy output
  docs/configuration.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug, enhancement

#156 Add ruff pre-commit and reformat files with it
  .pre-commit-config.yaml
  docs/conf.py
Labels: maintenance

#159 Update releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#160 Update to `jupyterlite-core >=0.2,<0.4`
  dev-environment.yml
  pyproject.toml
Labels: maintenance

#158 Raise informative error message when building man on older sphinx
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: maintenance

#161 Allow usage of global configuration values for `TryExamples` directive if provided by user
  docs/directives/try_examples.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement
