Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2024-01, with the labels that each got.

#118 Add option to disable TryExamples without rebuilding docs
  docs/directives/try_examples.md
  jupyterlite_sphinx/jupyterlite_sphinx.js
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#123 Update publish workflow to use the PyPI trusted publisher
  .github/workflows/publish-release.yml
Labels: maintenance

#129 Improve TryExamples customization
  docs/_static/try_examples.css
  docs/conf.py
  docs/directives/try_examples.md
  jupyterlite_sphinx/jupyterlite_sphinx.js
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: documentation, enhancement

#131 Misc parsing warnings.
  docs/_static/try_examples.css
  docs/configuration.md
  docs/directives/try_examples.md
  jupyterlite_sphinx/_try_examples.py
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement
