Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2024-02, with the labels that each got.

#133 Add a loading spinner for TryExamples directive.
  docs/directives/try_examples.md
  jupyterlite_sphinx/jupyterlite_sphinx.css
  jupyterlite_sphinx/jupyterlite_sphinx.js
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#134 Add processing of literal blocks in try examples directive
  jupyterlite_sphinx/_try_examples.py
Labels: bug

#135 Add a full screen "Open in tab" button
  docs/full.md
  jupyterlite_sphinx/jupyterlite_sphinx.js
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#139 Fix incorrect math processing
  jupyterlite_sphinx/_try_examples.py
Labels: documentation
