Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2024-07, with the labels that each got.

#182 `TryExamples` directive: fix missing kernels in CircleCI deployments
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#180 Strip tagged cells from `.ipynb` notebooks passed to the `NotebookLite` and `JupyterLite` directives
  docs/conf.py
  docs/configuration.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: enhancement

#185 Hotfix: cell metadata to parse should be `jupyterlite_sphinx_strip`
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#187 Resolve default-encoding errors on Windows
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#189 Fix invalid schema for `jupyterlite_sphinx_strip` tag when `strip_tagged_cells` is `True`
  docs/configuration.md
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#190 Restore SameFileError check when copying notebooks
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug

#193 Allow for JupyterLite 0.4.0
  pyproject.toml
Labels: maintenance
