Repository jupyterlite/jupyterlite-sphinx, pull requests merged in 2025-02, with the labels that each got.

#267 Update to `actions/upload-artifact@v4`
  .github/workflows/check-release.yml
Labels: maintenance

#263 BUG: Fix list of possible docstring section header patterns for `global_enable_try_examples`
  jupyterlite_sphinx/_try_examples.py
Labels: bug

#253 Update documentation around fullscreen usage of `jupyterlite-sphinx` apps
  docs/full.md
Labels: documentation

#271 BUG: Fix SciPy `make dist` doc workflow by ensuring jupyter is run with the current Python executable
  jupyterlite_sphinx/jupyterlite_sphinx.py
Labels: bug
